apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:openshift-apiserver-operator
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: openshift-apiserver-operator
  name: openshift-apiserver-operator
